require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'egersund_mobile_app' do
  config = use_native_modules!

    pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  use_react_native!(:path => config["reactNativePath"])

  target 'egersund_mobile_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
   post_install do |installer|
     flipper_post_install(installer)
   end
end

target 'egersund_mobile_app-tvOS' do
  # Pods for egersund_mobile_app-tvOS

  target 'egersund_mobile_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
